---
title: "Pair Assignment 2"
author: "Tori Dykes and Mansi Wadhwa"
date: "28 October 2016"
output: html_document
bibliography: bibliography.bib
---

## Proposed Research Question

Europe's youth population has seen significant tumult in the job market over the last ten years. The recession of 2008 hit all of Europe, but not all equally. Germany was largely lucky, with 11.9 percent youth unemployment in 2007, 11.3 percent in 2009, and just 7.3 percent today (based on OECD statistics). Ireland, on the other hand, has seen a significant increase in the youth unemployment rate, jumping from 9.1 percent in 2007 to 24.0 percent just two years later. The situation is only slightly better today, with a rate of 20.9 percent today. But of course, the poster children for youth unemployment in Europe today are Spain and Greece. Both countries already had fairly high youth unemployment rates in 2007 (18.1 percent for Spain and 22.7 percent for Greece), but they quickly ballooned in the years after. The numbers currently stand at 48.4 percent for Spain and 49.8 percent for Greece.

Out of this dire situation has arisen some notable political movements that feature youth support as a key tenet, such as Podemos in Spain and Syriza in Greece. Though the actual political efficacy of these parties can be debated, the rise of these movements raises questions about whether the frustration and desperation of unemployment (especially long-term unemployment) translates into political action or apathy. Do young people looking for work tend to feel abandoned by their government and choose to withdraw and detach from political activities? Or do they channel this frustration into a desire to change the system that by some accounts has failed them? 

Answering these questions is a complicated web of matching internal feelings to external action, plus there is the need to isolate the effects of unemployment from other factors that might encourage or discourage political engagement. Thus, gathering meaningful data and then being able to draw empirically-supported causal conclusions on this topic is not easy. To that end, we do not expect to be able to prove definitively that unemployment does or does not cause youths to engage more politically. But, we hope to at least illustrate how, if at all, the youth unemplyoment rate in European countries is related to the levels (and types) of political engagement.

In summation our working research question is, **"How does the youth unemployment rate in European countries affect the level and type of political engagement among youths in those same countries?"**

## Proposed Methodology and Data Sets

Our key sources of data will be the [OECD's datasets on Youth
Unemployment](https://data.oecd.org/unemp/youth-unemployment-rate.htm) and the [European Social Survey (ESS)](http://www.europeansocialsurvey.org/). The OECD data is available yearly, quarterly, and monthly, though we are only interested in yearly data. The ESS is a survey conducted every two years, starting in 2002. It aims to measure "the attitudes, beliefs and behaviour patterns of diverse populations in more than thirty nations." It specifies rigorous standards for sampling in each country in order to ensure the samples are representative. 

In order to analyse the relationship between, youth unemployment and the political engagement of the youth, we make use of the variables under the ESS theme Politics that capture multiple aspects of an individual's political participation and hence, are suitable for our analysis. While variables measuring respondent's voting in the last election, pariticipation in a political party, campaign or demonstration etc. reflect the actual involvement of the respondents in the political process, other variables measure interest in politcs, ease of comprehending political issues and trust in political institutions. The latter give us an understanding of a different dimension of the citizenry's political engagement. The ideological stance of the respondents is also measured through variables like placement on left-right scale, opinion on health services, education services, homosexuality,immigration, European unification etc. This further gives us more substantive data to add to our analysis.

Socio-demographic variables in the dataset discuss employment status in a detailed way - capturing the current status of employment, previous work, nature of employment, flexibility in employment, education levels etc. This gives us enough breadth to select relevant variables and carry out a specific yet well-directed analysis.

## Introductory Literature Review

The intersection and interaction between youth unemployment and political participation/engagement has been explored to varying degrees. The studies tend to investigate the basic premise that unemployment leads to social exclusion which leads to detachment from politics.

A study of unemployed youth in Geneva [@LorenziniGiugni] found that there was no real difference in the political involvement of unemployed and employed youth when looking at activities like protesting and contacting politicians, though unemployed youth were more likely to partake in consumer-based forms of involvement (e.g., boycotts or buying items with a political motivation). A different study made use of the same data set [@Lorenzini], focusing instead on the role life satisfaction plays in fostering political engagement. It found, somewhat unexpectedly, that among unemployed youth, life dissatisfaction actually decreases political engagement. In both studies, the results offer additional perspective on youth unemployment and political engagement, but the focus is quite narrow, since only youths in one specific European city are included. A study from Baglioni, Pasquale, and Theiss [-@BaglEtAl] suggested that associational membership can have a positive effect on keeping unemployed youths engaged in politics, the idea being that these memberships compensate for the role a normal working environment would have played in fostering political interest and connections.

On the more general subject of youth political participation, Sloam [-@Sloam14] looked at youths in the U.S., Great Britain and Germany. The main theme of his analysis is focusing on the evolution of political participation rather than its decline - it is true that fewer young people turn out in national elections these days, but they are more likely to instead partake in a greater variety of activities like demonstrating, campaigning and otherwise engaging with elected officials. Sloam ackonowledges the role unemployment and general social exclusion play in influencing whether and how youth engage themselves but doesn't offer a sophisticated analysis thereof. @KiiselEtAl took a similar approach, using ESS data to compare responses regarding political and civic participation of both Euroepan youths and adults. Similar to Sloam, they found lower levels of traditional political participation among youths today but greater involvement in "newer" forms of political engagement, although they did not find a striking difference between adult and youth involvement for any type of engagement. 

Thus while there is ample exploration of how youth political participation differs (if at all) from the political participation of adults, as well as if unemployment is related to political disengagement (both generally and among youths), there have been far fewer efforts to compare country-level data on youth unemployment with country-level data on youth political engagement. 



## Bibliography
